(function checkDevTools() {
  const start = performance.now();
  debugger; // This causes a pause if devtools open
  const end = performance.now();
  if (end - start > 100) { // threshold in ms
    alert('DevTools detected!');
    window.location.href = 'https://www.google.com'; // Redirect or block
  }
  setTimeout(checkDevTools, 1000);
})();

            <body>
  <div id="app"></div>

  <script>
    document.getElementById('app').innerHTML = `
      <h1>Welcome to the secret site!</h1>
      <p>This content is dynamically generated by JS.</p>
    `;
  </script>
</body>

setInterval(() => {
  if (
    window.outerWidth - window.innerWidth > 100 ||
    window.outerHeight - window.innerHeight > 100
  ) {
    alert('DevTools is open! Closing...');
    window.close(); // Attempt to close tab
  }
}, 500);

                            (function detectDebugger() {
  let isOpen = false;
  const devtools = /./;
  devtools.toString = function() {
    isOpen = true;
    alert('DevTools is open! Reloading...');
    location.reload();
  };
  console.log('%c', devtools);
  if (isOpen) {
    // Handle detection
  }
  setTimeout(detectDebugger, 1000);
})();

                            body {
  -webkit-user-select: none; /* Safari */
  -moz-user-select: none; /* Firefox */
  -ms-user-select: none; /* IE10+/Edge */
  user-select: none; /* Standard */
}

                            document.addEventListener('dragstart', e => e.preventDefault());
(function createOverlay() {
  let overlay = document.getElementById('blocker');
  if (!overlay) {
    overlay = document.createElement('div');
    overlay.id = 'blocker';
    overlay.style.position = 'fixed';
    overlay.style.top = 0;
    overlay.style.left = 0;
    overlay.style.width = '100vw';
    overlay.style.height = '100vh';
    overlay.style.zIndex = 999999;
    overlay.style.backgroundColor = 'transparent';
    document.body.appendChild(overlay);
  }
  setTimeout(createOverlay, 500);
})();

                            setInterval(() => {
  console.clear();
  console.log('%cStop trying to inspect!', 'color: red; font-size: 20px; font-weight: bold;');
}, 1000);

document.getElementById('dataForm').addEventListener('submit', async (e) => {
  e.preventDefault(); // Stop form from submitting normally

  const form = e.target;
  const formData = new FormData(form);
  const data = Object.fromEntries(formData.entries());

  try {
    const response = await fetch('/api/data', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });

    const result = await response.json();

    document.getElementById('response').textContent = `Server says: ${result.message}`;
  } catch (error) {
    document.getElementById('response').textContent = 'Error contacting server.';
    console.error('Error:', error);
  }
});

fetch('/api/data', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify(data),
});
